/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;


/**
 *
 * @author kazii
 *
 *
 */
public class DefaulterListForm extends javax.swing.JFrame {
    
    DefaultTableModel model;

    public DefaulterListForm() {
        initComponents();
        setDefaulterListDetailTable();
    }

    public void setDefaulterListDetailTable(){
        long  l= System.currentTimeMillis();
        java.sql.Date today = new java.sql.Date(l);
        try{
            Connection conc = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "toor");
            String sql = "select * from borrow where due_date < ? and status = ?";
            PreparedStatement pst = conc.prepareStatement(sql);
            pst.setDate(1,today);
            pst.setString(2, "pending");
            ResultSet rs = pst.executeQuery();
            while (rs.next()){
                String bid = rs.getString("b_id");
                String issue=rs.getString("issue_date");
                String due =rs.getString("due_date");
                String status=rs.getString("status");
                Object obj[] ={bid,"","",issue,due,status};
            }
        }catch(Exception e ){
            e.printStackTrace();
        }   JOptionPane.showMessageDialog(this, "Can't Fetched Record");
    }
    
   
               
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //Intialization To Form
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookDetailsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        teach_detail2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        defaulterTable = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Books");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        BookDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back);

        BookDetailsPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        teach_detail2.setBackground(new java.awt.Color(102, 102, 255));
        teach_detail2.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        teach_detail2.setForeground(new java.awt.Color(255, 51, 51));
        teach_detail2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teach_detail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Edit_Property_50px.png"))); // NOI18N
        teach_detail2.setText("  Defaulters List");
        teach_detail2.setAutoscrolls(true);
        BookDetailsPanel.add(teach_detail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 330, 70));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        BookDetailsPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 320, 5));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        defaulterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Title", "Borrower Name", "Issue Date", "Due Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        defaulterTable.setColorBackgoundHead(new java.awt.Color(255, 51, 51));
        defaulterTable.setColorBordeFilas(new java.awt.Color(255, 51, 51));
        defaulterTable.setColorFilasForeground1(new java.awt.Color(255, 51, 51));
        defaulterTable.setColorFilasForeground2(new java.awt.Color(255, 51, 51));
        defaulterTable.setColorSelBackgound(new java.awt.Color(102, 102, 255));
        defaulterTable.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        defaulterTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        defaulterTable.setFuenteHead(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        defaulterTable.setRowHeight(30);
        defaulterTable.setRowMargin(1);
        defaulterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaulterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(defaulterTable);

        BookDetailsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 1240, 490));

        getContentPane().add(BookDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void defaulterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterTableMouseClicked

    }//GEN-LAST:event_defaulterTableMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefaulterListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefaulterListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefaulterListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefaulterListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaulterListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookDetailsPanel;
    private javax.swing.JLabel back;
    private rojeru_san.complementos.RSTableMetro defaulterTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel teach_detail2;
    // End of variables declaration//GEN-END:variables
}
