/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Color;

/**
 *
 * @author kazii
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    Color mouseEnter = new Color(0,0,0);
    Color mouseExit= new Color (51,51,51);
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        manageBookPanel = new javax.swing.JPanel();
        manage_books = new javax.swing.JLabel();
        viewRecordPanel = new javax.swing.JPanel();
        view_record = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        log_out = new javax.swing.JLabel();
        issueBookPanel = new javax.swing.JPanel();
        issue_book = new javax.swing.JLabel();
        returnBookPanel = new javax.swing.JPanel();
        return_book = new javax.swing.JLabel();
        manageStudentPanel = new javax.swing.JPanel();
        manage_student = new javax.swing.JLabel();
        viewIssueBook = new javax.swing.JPanel();
        view_issue = new javax.swing.JLabel();
        defaulter = new javax.swing.JPanel();
        defualter_list = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        nob = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        nos = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        ib = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        dl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new rojeru_san.complementos.RSTableMetro();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new rojeru_san.complementos.RSTableMetro();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 2, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("Welome, Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 240, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SL Library");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 7, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 60));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageBookPanel.setBackground(new java.awt.Color(51, 51, 51));
        manageBookPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageBookPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageBookPanelMouseExited(evt);
            }
        });
        manageBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manage_books.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        manage_books.setForeground(new java.awt.Color(255, 255, 255));
        manage_books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        manage_books.setText("  Manage Books");
        manage_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manage_booksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manage_booksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manage_booksMouseExited(evt);
            }
        });
        manageBookPanel.add(manage_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 50));

        jPanel4.add(manageBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, 50));

        viewRecordPanel.setBackground(new java.awt.Color(51, 51, 51));
        viewRecordPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRecordPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRecordPanelMouseExited(evt);
            }
        });
        viewRecordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_record.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        view_record.setForeground(new java.awt.Color(255, 255, 255));
        view_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        view_record.setText("  View Records");
        view_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_recordMouseExited(evt);
            }
        });
        viewRecordPanel.add(view_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 50));

        jPanel4.add(viewRecordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Features");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Library_32px.png"))); // NOI18N
        jLabel7.setText("   SL Dashboard");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel8.setText("    Home Page");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 50));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        log_out.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        log_out.setForeground(new java.awt.Color(255, 255, 255));
        log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        log_out.setText("  Logout");
        log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_outMouseClicked(evt);
            }
        });
        jPanel8.add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 50));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 280, 50));

        issueBookPanel.setBackground(new java.awt.Color(51, 51, 51));
        issueBookPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBookPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issueBookPanelMouseExited(evt);
            }
        });
        issueBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issue_book.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        issue_book.setForeground(new java.awt.Color(255, 255, 255));
        issue_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        issue_book.setText("  Issue Book");
        issue_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issue_bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issue_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issue_bookMouseExited(evt);
            }
        });
        issueBookPanel.add(issue_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 50));

        jPanel4.add(issueBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 50));

        returnBookPanel.setBackground(new java.awt.Color(51, 51, 51));
        returnBookPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnBookPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnBookPanelMouseExited(evt);
            }
        });
        returnBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        return_book.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        return_book.setForeground(new java.awt.Color(255, 255, 255));
        return_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        return_book.setText("  Return Book");
        return_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                return_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                return_bookMouseExited(evt);
            }
        });
        returnBookPanel.add(return_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 40));

        jPanel4.add(returnBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 50));

        manageStudentPanel.setBackground(new java.awt.Color(51, 51, 51));
        manageStudentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageStudentPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageStudentPanelMouseExited(evt);
            }
        });
        manageStudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manage_student.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        manage_student.setForeground(new java.awt.Color(255, 255, 255));
        manage_student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        manage_student.setText("  Manage People");
        manage_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manage_studentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manage_studentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manage_studentMouseExited(evt);
            }
        });
        manageStudentPanel.add(manage_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 50));

        jPanel4.add(manageStudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 280, 50));

        viewIssueBook.setBackground(new java.awt.Color(51, 51, 51));
        viewIssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewIssueBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewIssueBookMouseExited(evt);
            }
        });
        viewIssueBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_issue.setBackground(new java.awt.Color(51, 51, 51));
        view_issue.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        view_issue.setForeground(new java.awt.Color(255, 255, 255));
        view_issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Books_26px.png"))); // NOI18N
        view_issue.setText(" Issue & Return Records");
        view_issue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_issueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_issueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_issueMouseExited(evt);
            }
        });
        viewIssueBook.add(view_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 50));

        jPanel4.add(viewIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 280, 50));

        defaulter.setBackground(new java.awt.Color(51, 51, 51));
        defaulter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defaulterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defaulterMouseExited(evt);
            }
        });
        defaulter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        defualter_list.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        defualter_list.setForeground(new java.awt.Color(255, 255, 255));
        defualter_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        defualter_list.setText("  Defaulter List");
        defualter_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defualter_listMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defualter_listMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defualter_listMouseExited(evt);
            }
        });
        defaulter.add(defualter_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 50));

        jPanel4.add(defaulter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 280, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 280, 730));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        nob.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        nob.setText(" 10");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(nob, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nob)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 100));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText(" No of Books");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        nos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_People_50px.png"))); // NOI18N
        nos.setText(" 10");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(nos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(nos)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 200, 100));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("No of Students");
        jPanel14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 30));

        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        ib.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        ib.setText(" 10");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(ib, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ib)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 200, 100));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Issued Books");
        jPanel14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, 30));

        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        dl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        dl.setText(" 10");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(dl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dl)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 200, 100));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Defaulter List");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, 30));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Title", "Author", "Book Edition", "Available Copies", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookTable.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        bookTable.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        bookTable.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        bookTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bookTable.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bookTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookTable.setFuenteHead(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookTable.setRowHeight(30);
        bookTable.setRowMargin(1);
        jScrollPane1.setViewportView(bookTable);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 970, 210));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Books Detail");
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Phone", "Email", "Books Issue", "Fine"
            }
        ));
        studentTable.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        studentTable.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        studentTable.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        studentTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        studentTable.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studentTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studentTable.setFuenteHead(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentTable.setRowHeight(30);
        studentTable.setRowMargin(1);
        jScrollPane2.setViewportView(studentTable);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 970, 210));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Student Detail:");
        jPanel14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1080, 690));

        setSize(new java.awt.Dimension(1371, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manage_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_booksMouseClicked
        // TODO add your handling code here:
        
        ManageBookForm books=new ManageBookForm();
        books.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage_booksMouseClicked

    private void manageBookPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookPanelMouseEntered
        // TODO add your handling code here:
        manageBookPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_manageBookPanelMouseEntered

    private void manageBookPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookPanelMouseExited
        // TODO add your handling code here:
        manageBookPanel.setBackground(mouseExit);
    }//GEN-LAST:event_manageBookPanelMouseExited

    private void manage_booksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_booksMouseEntered
        // TODO add your handling code here:
        manageBookPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_manage_booksMouseEntered

    private void manage_booksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_booksMouseExited
        // TODO add your handling code here:
        manageBookPanel.setBackground(mouseExit);
    }//GEN-LAST:event_manage_booksMouseExited

    private void manage_studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_studentMouseEntered
        // TODO add your handling code here:
         manageStudentPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_manage_studentMouseEntered

    private void manage_studentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_studentMouseExited
        // TODO add your handling code here:
         manageStudentPanel.setBackground(mouseExit);
    }//GEN-LAST:event_manage_studentMouseExited

    private void manageStudentPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentPanelMouseEntered
        // TODO add your handling code here:
                 manageStudentPanel.setBackground(mouseEnter);

    }//GEN-LAST:event_manageStudentPanelMouseEntered

    private void manageStudentPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentPanelMouseExited
        // TODO add your handling code here:
                 manageStudentPanel.setBackground(mouseExit);

    }//GEN-LAST:event_manageStudentPanelMouseExited

    private void issueBookPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookPanelMouseEntered
        // TODO add your handling code here:
        issueBookPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_issueBookPanelMouseEntered

    private void issueBookPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookPanelMouseExited
        // TODO add your handling code here:
        issueBookPanel.setBackground(mouseExit);
    }//GEN-LAST:event_issueBookPanelMouseExited

    private void issue_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_bookMouseEntered
        // TODO add your handling code here:
        issueBookPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_issue_bookMouseEntered

    private void issue_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_bookMouseExited
        // TODO add your handling code here:
        issueBookPanel.setBackground(mouseExit);
    }//GEN-LAST:event_issue_bookMouseExited

    private void return_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_bookMouseEntered
        // TODO add your handling code here:
        returnBookPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_return_bookMouseEntered

    private void return_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_bookMouseExited
        // TODO add your handling code here:
        returnBookPanel.setBackground(mouseExit);
    }//GEN-LAST:event_return_bookMouseExited

    private void returnBookPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookPanelMouseEntered
        // TODO add your handling code here:
        returnBookPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_returnBookPanelMouseEntered

    private void returnBookPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookPanelMouseExited
        // TODO add your handling code here:
        returnBookPanel.setBackground(mouseExit);
    }//GEN-LAST:event_returnBookPanelMouseExited

    private void view_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_recordMouseEntered
        // TODO add your handling code here:
        viewRecordPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_view_recordMouseEntered

    private void view_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_recordMouseExited
        // TODO add your handling code here:
        viewRecordPanel.setBackground(mouseExit);
    }//GEN-LAST:event_view_recordMouseExited

    private void viewRecordPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordPanelMouseEntered
        // TODO add your handling code here:
        viewRecordPanel.setBackground(mouseEnter);
    }//GEN-LAST:event_viewRecordPanelMouseEntered

    private void viewRecordPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordPanelMouseExited
        // TODO add your handling code here:
        viewRecordPanel.setBackground(mouseExit);
    }//GEN-LAST:event_viewRecordPanelMouseExited

    private void view_issueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_issueMouseEntered
        // TODO add your handling code here:
        viewIssueBook.setBackground(mouseEnter);
    }//GEN-LAST:event_view_issueMouseEntered

    private void view_issueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_issueMouseExited
        // TODO add your handling code here:
        viewIssueBook.setBackground(mouseExit);
    }//GEN-LAST:event_view_issueMouseExited

    private void viewIssueBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewIssueBookMouseEntered
        // TODO add your handling code here:
        viewIssueBook.setBackground(mouseEnter);
    }//GEN-LAST:event_viewIssueBookMouseEntered

    private void viewIssueBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewIssueBookMouseExited
        // TODO add your handling code here:
        viewIssueBook.setBackground(mouseExit);
    }//GEN-LAST:event_viewIssueBookMouseExited

    private void defualter_listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defualter_listMouseEntered
        // TODO add your handling code here:
        defaulter.setBackground(mouseEnter);
    }//GEN-LAST:event_defualter_listMouseEntered

    private void defualter_listMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defualter_listMouseExited
        // TODO add your handling code here:
        defaulter.setBackground(mouseExit);
    }//GEN-LAST:event_defualter_listMouseExited

    private void defaulterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterMouseEntered
        // TODO add your handling code here:
        defaulter.setBackground(mouseEnter);
    }//GEN-LAST:event_defaulterMouseEntered

    private void defaulterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterMouseExited
        // TODO add your handling code here:
        defaulter.setBackground(mouseExit);
    }//GEN-LAST:event_defaulterMouseExited

    private void log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outMouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_log_outMouseClicked

    private void manage_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_studentMouseClicked
        // TODO add your handling code here:
        ManageStudentForm manage = new ManageStudentForm();
        manage.setVisible(true);
        manage.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_manage_studentMouseClicked

    private void issue_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_bookMouseClicked
        // TODO add your handling code here:
        IssueBookForm issue = new IssueBookForm();
        issue.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_issue_bookMouseClicked

    private void return_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_bookMouseClicked
        // TODO add your handling code here:
        ReturnBookForm returnbook = new ReturnBookForm();
        returnbook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_return_bookMouseClicked

    private void view_issueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_issueMouseClicked
        // TODO add your handling code here:
        IssueBookRecordForm issue_rec = new IssueBookRecordForm();
        issue_rec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_issueMouseClicked

    private void view_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_recordMouseClicked
        // TODO add your handling code here:
        StudentRecordForm stu = new StudentRecordForm();
        stu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_recordMouseClicked

    private void defualter_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defualter_listMouseClicked
        // TODO add your handling code here:
        DefaulterListForm dl= new DefaulterListForm();
        dl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_defualter_listMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro bookTable;
    private javax.swing.JPanel defaulter;
    private javax.swing.JLabel defualter_list;
    private javax.swing.JLabel dl;
    private javax.swing.JLabel ib;
    private javax.swing.JPanel issueBookPanel;
    private javax.swing.JLabel issue_book;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel log_out;
    private javax.swing.JPanel manageBookPanel;
    private javax.swing.JPanel manageStudentPanel;
    private javax.swing.JLabel manage_books;
    private javax.swing.JLabel manage_student;
    private javax.swing.JLabel nob;
    private javax.swing.JLabel nos;
    private javax.swing.JPanel returnBookPanel;
    private javax.swing.JLabel return_book;
    private rojeru_san.complementos.RSTableMetro studentTable;
    private javax.swing.JPanel viewIssueBook;
    private javax.swing.JPanel viewRecordPanel;
    private javax.swing.JLabel view_issue;
    private javax.swing.JLabel view_record;
    // End of variables declaration//GEN-END:variables
}
