/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;

/**
 *
 * @author kazii
 *
 *
 */
public class IssueBookRecordForm extends javax.swing.JFrame {

    DefaultTableModel model;

    public IssueBookRecordForm() {
        initComponents();
        setIssueBooksDetailTable();
    }

    public void setIssueBooksDetailTable() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "");

            Statement stmt = con.createStatement();
            ResultSet rset = stmt.executeQuery("select * from borrow");

            while (rset.next()) {

                String IID = rset.getString(1);
                String BID = rset.getString(2);
                String SID = rset.getString(3);
                String BrID = rset.getString(4);
                String IDate = rset.getString(5);
                String DDate = rset.getString(6);
                String Status = rset.getString(7);

//                 String cGender= rset.getString(7);
                Object[] obj = {IID, BID, "Book Title", BrID, "Borrower Name", SID, "Staff Name", IDate, DDate, Status};
//                Object [] obj = {"1","2","3","4","5","200","500"};
                model = (DefaultTableModel) issueRecordTable.getModel();
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Method That FFetched Records from database according to given date
    public void searchRecords() {
        Date fromDate = from.getDatoFecha();
        Date toDate = to.getDatoFecha();

        if (fromDate.equals("") || toDate.equals("")) {
            messageLabel.setText("Please Select Dates...");
        } else {

            long lfrom = fromDate.getTime();
            long lto = toDate.getTime();

            java.sql.Date dfromDate = new java.sql.Date(lfrom);
            java.sql.Date dtoDate = new java.sql.Date(lto);
            try {
                  Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "");
                  String sql = "select * from borrows where isssue_date between ? and ? ";
                  PreparedStatement pst = con.prepareStatement(sql);
                  pst.setDate(1, dfromDate);
                  pst.setDate(2, dtoDate);
                  
                  
                  ResultSet rs=pst.executeQuery();
                  if (rs.next()){
                    messageLabel.setText("Record not found.");
                  }
                  while (rs.next()){
                      String IID = rs.getString(1);
                String BID = rs.getString(2);
                String SID = rs.getString(3);
                String BrID = rs.getString(4);
                String IDate = rs.getString(5);
                String DDate = rs.getString(6);
                String Status = rs.getString(7);

//                 String cGender= rset.getString(7);
                Object[] obj = {IID, BID, "Book Title", BrID, "Borrower Name", SID, "Staff Name", IDate, DDate, Status};
//                Object [] obj = {"1","2","3","4","5","200","500"};
                model = (DefaultTableModel) issueRecordTable.getModel();
                model.addRow(obj);
                  }
                  
                
            }catch(Exception e){
                
            }

        }
    }

    //Method to clear Table
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) issueRecordTable.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //Intialization To Form
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookDetailsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        teach_detail1 = new javax.swing.JLabel();
        fnameLabel6 = new javax.swing.JLabel();
        from = new rojeru_san.componentes.RSDateChooser();
        to = new rojeru_san.componentes.RSDateChooser();
        fnameLabel7 = new javax.swing.JLabel();
        clear = new necesario.MaterialButton();
        search = new necesario.MaterialButton();
        messageLabel = new javax.swing.JLabel();
        viewRecordPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueRecordTable = new rojeru_san.complementos.RSTableMetro();
        Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Books");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookDetailsPanel.setBackground(new java.awt.Color(102, 102, 255));
        BookDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        back.setBackground(new java.awt.Color(102, 102, 255));
        back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back);

        BookDetailsPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        BookDetailsPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 270, 5));

        teach_detail1.setBackground(new java.awt.Color(102, 102, 255));
        teach_detail1.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        teach_detail1.setForeground(new java.awt.Color(255, 255, 255));
        teach_detail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teach_detail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        teach_detail1.setText("  Issue Books Details");
        teach_detail1.setAutoscrolls(true);
        BookDetailsPanel.add(teach_detail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 400, 100));

        fnameLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fnameLabel6.setForeground(new java.awt.Color(255, 255, 255));
        fnameLabel6.setText("From:");
        BookDetailsPanel.add(fnameLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 60, 30));

        from.setBackground(new java.awt.Color(102, 102, 255));
        from.setColorBackground(new java.awt.Color(102, 102, 255));
        from.setColorButtonHover(new java.awt.Color(102, 102, 102));
        from.setColorDiaActual(new java.awt.Color(102, 102, 255));
        from.setColorForeground(new java.awt.Color(255, 255, 255));
        from.setColorSelForeground(new java.awt.Color(102, 102, 255));
        from.setPlaceholder("Issue Date");
        BookDetailsPanel.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 220, 30));

        to.setBackground(new java.awt.Color(102, 102, 255));
        to.setColorBackground(new java.awt.Color(102, 102, 255));
        to.setColorButtonHover(new java.awt.Color(102, 102, 102));
        to.setColorDiaActual(new java.awt.Color(102, 102, 255));
        to.setColorForeground(new java.awt.Color(255, 255, 255));
        to.setColorSelForeground(new java.awt.Color(102, 102, 255));
        to.setPlaceholder("Due Date");
        BookDetailsPanel.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 220, 30));

        fnameLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fnameLabel7.setForeground(new java.awt.Color(255, 255, 255));
        fnameLabel7.setText("To:");
        BookDetailsPanel.add(fnameLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 60, 30));

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setForeground(new java.awt.Color(255, 51, 51));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        BookDetailsPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 130, 120, 40));

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setForeground(new java.awt.Color(102, 102, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        BookDetailsPanel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 80, 120, 40));

        messageLabel.setBackground(new java.awt.Color(102, 102, 255));
        messageLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 51, 51));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookDetailsPanel.add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 400, 50));

        getContentPane().add(BookDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 200));

        viewRecordPanel.setBackground(new java.awt.Color(255, 255, 255));
        viewRecordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        issueRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue ID", "Book ID ", "Book Title", "Borrower ID", "Borrower Name", "Staff ID", "Staff Name", "Issue Date", "Due Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        issueRecordTable.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        issueRecordTable.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        issueRecordTable.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        issueRecordTable.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        issueRecordTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        issueRecordTable.setFuenteHead(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        issueRecordTable.setRowHeight(30);
        issueRecordTable.setRowMargin(1);
        issueRecordTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueRecordTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(issueRecordTable);

        viewRecordPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1330, 430));

        Label.setBackground(new java.awt.Color(102, 102, 255));
        Label.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        Label.setForeground(new java.awt.Color(102, 102, 255));
        Label.setText("Details:");
        viewRecordPanel.add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 400, 50));

        getContentPane().add(viewRecordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1370, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        setIssueBooksDetailTable();
        

    }//GEN-LAST:event_clearActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        searchRecords();
        

    }//GEN-LAST:event_searchActionPerformed

    private void issueRecordTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueRecordTableMouseClicked
//        int rowNumber = issueRecordTable.getSelectedRow();
//        TableModel model = issueRecordTable.getModel();
//        c_id.setText(model.getValueAt(rowNumber, 0).toString());
//        c_first.setText(model.getValueAt(rowNumber, 1).toString());
//        //        s_last.setText(model.getValueAt(rowNumber, 2).toString());
//        c_cnic.setText(model.getValueAt(rowNumber, 2).toString());
//        c_phone.setText(model.getValueAt(rowNumber, 3).toString());
//        c_address.setText(model.getValueAt(rowNumber, 4).toString());
//        c_gender.setText(model.getValueAt(rowNumber, 5).toString());
//        //        t_gender.setText(model.getValueAt(rowNumber, 6).toString());
//        //        t_department.setText(model.getValueAt(rowNumber, 7).toString());

    }//GEN-LAST:event_issueRecordTableMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBookRecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBookRecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBookRecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBookRecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBookRecordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookDetailsPanel;
    private javax.swing.JLabel Label;
    private javax.swing.JLabel back;
    private necesario.MaterialButton clear;
    private javax.swing.JLabel fnameLabel6;
    private javax.swing.JLabel fnameLabel7;
    private rojeru_san.componentes.RSDateChooser from;
    private rojeru_san.complementos.RSTableMetro issueRecordTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLabel;
    private necesario.MaterialButton search;
    private javax.swing.JLabel teach_detail1;
    private rojeru_san.componentes.RSDateChooser to;
    private javax.swing.JPanel viewRecordPanel;
    // End of variables declaration//GEN-END:variables
}
